name = "LowChowRankPolynomial"
uuid = "1f5e9269-399d-4900-9a65-deebe4700a3d"
authors = ["timotheMenard <menardtimothee@gmail.com>"]
version = "0.1.0"

[deps]
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
